name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            asset_name: virtual-thermal-printer-linux
          - os: macos-latest
            asset_name: virtual-thermal-printer-macos
          - os: windows-latest
            asset_name: virtual-thermal-printer-windows.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Compile application
        run: deno task compile

      - name: Rename executable
        run: mv virtual-thermal-printer ${{ matrix.asset_name }}
        if: matrix.os != 'windows-latest'

      - name: Rename executable (Windows)
        run: mv virtual-thermal-printer.exe ${{ matrix.asset_name }}
        if: matrix.os == 'windows-latest'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
